### ISSUE TITLE
 Banshee compile error: cannot convert from 'const wchar_t [1]' to 'BSTR' on Windows

### ISSUE THREAD

**Issue by htmlboss** [BearishSun/BansheeEngine#118]
VS 2017.5,

This error occurs in: `BsWin32Input.cpp`, `BsWin32Mouse.cpp`, `BsWin32Keyboard.cpp`, `BsWin32Gamepad.cpp` with the latest commit from master (`42e3c31`).

`Error	C2440	'default argument': cannot convert from 'const wchar_t [1]' to 'BSTR' (compiling source file C:\Users\Nabil\Documents\GitHub\BansheeEngine\Source\BansheeCore\Win32\BsWin32Input.cpp)	BansheeCore	C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\wbemdisp.h	1049`

Verbose output:
`6>C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\wbemdisp.h(1049): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings) (compiling source file C:\Users\Nabil\Documents\GitHub\BansheeEngine\Source\BansheeCore\Win32\BsWin32Input.cpp)
`

I suppose the switch `/Zc:strictStrings` is being set somewhere? Another culprit could be `/permissive`.

Stack Overflow link: https://stackoverflow.com/questions/37204166/error-c2440-default-argument-cannot-convert-from-const-wchar-t-1-to-bst/37205880

**Comment by BearishSun** [comment]
Must be some changes in VS 2017.5, as it compiles fine on VS 2017.4. I'm updating right now and we'll see then.

**Comment by BearishSun** [comment]
The issue seems to be a particular Windows SDK version, 10.0.15063.0 (I'm guessing it doesn't play well with `/permissive-`). If you install the latest one available in VS Installer, which is 10.0.16299.0 it should compile fine. After you will need to re-generate the build files using CMake, and they should automatically be configured to use the latest SDK.
