### ISSUE TITLE
[QUESTION] Why is the "internal" folder get so big?

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#148]
Hi, 

I've just checked the folders of my current test project:
Internal - 1.66Gb
Ressources - 190Mb

Looking inside the internal folder, I see files with ids, and it seem that all the textures and models are stored there like in raw format without any compression. I could be wrong but I think everything is put like this for getting the fastest loading speed possible for the assets since the engine don't have to "translate" and uncompress the assets to use them and would make your asynchronous loading feature work.

If it's true, then for models I don't think it would be a big issue, but for textures, I have models with 2-3 textures on them of 2048px x 2048px. In my ressources folder, they are all in PNG (lossless) and still the Internal folder is about 10 times the size of theses ressources.

Is there something planned so that we could do data exchange of our project sources like asset packs? (For example assets packs with scenes in Unity).  Right now my test projet would be near 2Gb of download when only 190mb of assets are used. And for looking at a scene you need the internal folder.

**Comment by NathanWarden** [comment]
It's most likely because even though your PNGs are lossless, they are still compressed. For instance, I just made an all white texture that's 2048x2048 and it saves losslessly at 60 kb. But, when you actually do the math if it were saving each and every pixel it should be 12 MB. In order for the texture to map to the GPU (for 3D at least) it needs to be in a particular format the GPU can use such as ETC/DXT/etc which are all much larger than most PNG files. It looks like Godot uses both ETC2 and S3TC (probably for per device speed optimization), but this is why the import folder is larger than your actual resources, because Godot has converted your textures into format's that can be mapped to the GPU memory, which tend to be much larger than even lossless PNGs.

What is the compression mode in your PNG import settings? If it's set to Video RAM, maybe try using Lossless there just to see if this is the cause :) If it's for a 3D game I believe setting it to Video RAM is the correct setting. I think for 2D you can use the others (although I may be wrong about that).

The same png I mentioned above comes in at 16.9 KB for Lossless mode, but 2.8 MB for Video RAM mode.

**Comment by BearishSun** [comment]
By default all imported textures are in raw uncompressed format, which is quite big and likely the biggest culprit of the Internal folder size. You can change the texture format using the import options in the inspector. A compressed format like BC1 is best for RGB data. BC3 for RGBA, BC4 for single-channel data (like metalness/roughness), BC5 for dual-channel textures, BC6 for HDR and BC7 is a higher quality version of BC1 and BC3 essentially (but such textures are slower to use by the GPU). 

There is an additional compression setting supported for all resources types internally, but isn't being used by the editor at the moment. Eventually it will be exposed as well, and reduce the size of the folder further.

There is no asset pack feature planned at the moment, but when the project is more mature, certainly.

**Comment by NathanWarden** [comment]
@BearishSun Oops, not the first time I commented on a game engine thinking it was another one (Godot in this case), haha :D

Thanks for all your hard work on this engine Marko :)

**Comment by christianclavet** [comment]
Hi,

Thanks this could reduce a lot my project size on disk!

I've tried to change the format of a few textures to BC1 to see, but got a crash when I clicked on the reimport button, then when loading back, a ressource cannot be loaded. When clicking back on the texture, it crash again with another exception.

I'm using DX11 on Windows at the moment. The trace of calls seem to go in the RenderApi.dll and D3D11TextureLock functions.

**Comment by BearishSun** [comment]
The issue with the BC formats should be resolved, 778dc93339a0951511fe1a5baeb02b32167cea10. Although I didn't test all formats yet, so there could still be some problems.

**Comment by christianclavet** [comment]
Thanks, I tried BC1 and BC7 and they seem to work (Have a little doubt on BC7 because it froze the application for a moment, but finally resumed)
My "scripting" test, that I've sent was around 6 Mb in a Zipped file. Re-compressed the textures with BC1 for the general textures, and used BC7 for the skybox texture, and redone the archive, result is now around 2 Mb! I'll do that on my test project with the ship to see. I think that will improve a lot the size and would help a lot if I want to give back the project later...
