### ISSUE TITLE
Source tree organization (Not a real issue)

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#176]
So this is not exactly an issue. I just figured this may be the place to get the quickest answer to the question.

Why is the source tree essentially flat?

Meaning: applications, libraries and plugins are all placed in the "Source" directory on the same level.

I figure you have your reasons for doing it that way.

However, are you open to changing the structure of the source tree?

I suppose something like this would fit well given the current components in the source tree.

Source/
----Core/
----Editor/
----Engine/
----Plugins/

I got the idea of working on an installer for Banshee and got the idea for this.

**Comment by BearishSun** [comment]
Initially there were just a few plugins and there wasn't much of an issue, and I haven't changed it since. But it has been bothering me as well and I do plan on cleaning it up.

As you suggest all plugins will be moved into their own folder, and I also want to cleanly separate the framework and the editor. Examples will most likely want to be moved into their own repository so I don't need to worry about filling the repo up with binary assets.

**Comment by jayrulez** [comment]
Sounds good. Do you have a projected time line in which you would like to get this done?

**Comment by christianclavet** [comment]
Newbie question here: So I could host my Banshee 3D demos/examples on github?

**Comment by BearishSun** [comment]
@jayrulez Ideally within the next month.

@christianclavet There's a repository limit of 1GB, and maximum file size of 100MB, so it's only good for small projects (but you can buy more storage). Also Git isn't a good solution for projects with non-text files that change often because it stores every single version of the file, which means the repository size bloats up really fast.

**Comment by christianclavet** [comment]
Ok. I could do it, but update a lot less then. Thanks!

**Comment by BearishSun** [comment]
The reorganization is done. Entire engine core (the framework) has been moved into a separate repository: https://github.com/GameFoundry/bsf, and its folder structure has been organized to separate plugins and the foundation system.

This repository now links to the framework repository, and on its own just contains the editor and scripting components.

**Comment by christianclavet** [comment]
Wow! Just seen this! Congrats! This is really awesome! As this framework could be a QT equivalent of a framework optimized for 3D Graphics! I've rarely seen a framework, that could have docked windows being able to detach them completely and work with multiple monitors, and Banshee 3D can! And for writing 3D applications, this is a highly desired feature!
