### ISSUE TITLE
Editor crashes when adding script to empty project.

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#201]
[20180421_1740.zip](https://github.com/BearishSun/BansheeEngine/files/1935054/20180421_1740.zip)

The editor crashes when adding a script to an empty project.

I am using release version built from the latest commit.

**Comment by jayrulez** [comment]
Tracked the issue down to this method: String md5(const String& source) in BsUtil.cpp

buf[32] = '\0';

Something seems to be weird with the string class.

When I am debugging, the reported size in the debugger is always 0 even though it has the md5 value as content of the string.

**Comment by jayrulez** [comment]
Simply commenting that null termination line fixes the problem. Do we really need that line?

**Comment by jayrulez** [comment]
Using buf.resize(32) instead of buf.reserve(33) also prevents th issue.

**Comment by jayrulez** [comment]
There seem to be a lot of instability issues since the recent string refactoring. The editor has become pretty unusable.

Attempting to rename a scene object crashes the editor.

Error: cannot seek string iterator past end.

**Comment by BearishSun** [comment]
Thanks for the report. Both issues should now be resolved.

**Comment by jonesmz** [comment]
The goal behind using reserve instead of resize was to avoid paying the cost of initializing the string value_type (char) to zero, but for such a small string it's probably irrelevant. Apparently the way string works is different for your platform than my own, but clearly it shouldn't be crashing anywhere.

Thanks for catching and cleaning up my mess.
