### ISSUE TITLE
BoxCollider does not work properly  when i modify the center attribute in the banshee editor and rotate SceneObject

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#225]
I tracked the relevant code.
	bsf/Source/Foundation/bsfCore/Components/BsCCollider.cpp(277 line and 286 line)

relativePos = relativePos + myRot.rotate(mLocalPosition * scale);

This 'mLocalPosition' is already in the local coordinate system , why rotate it.
I have modified the line code like this
relativePos = relativePos + mLocalPosition * scale;
so the BoxCollider can work properly.

**Comment by BearishSun** [comment]
Thanks, I'll make the change after I get a chance to test it.

**Comment by BearishSun** [comment]
If that rotation is removed, then `mLocalPosition` will not rotate with its parent object. 

For example, imagine you had a collider at origin `(0, 0, 0)`, not rotated. If you set `mLocalPosition` to `(10, 0, 0)` (10 units to the right), the world space position would also be `(10, 0, 0)` (since collider isn't translated or rotated). Then if you rotated the collider by 90 degrees around the Y axis, you would expect  world position of `mLocalPosition` to rotate with it, but it would instead remain the original `(10, 0, 0)`, which is not the expected behavior.

I've also ran some tests in the editor and all offset/rotation combinations I have tried have appeared to place the collider at the correct location. If you let me know of the exact issue you are having I can take a closer look.

Note that I have just fixed an issue with Collider visualizations in the editor, that caused incorrect offset to be applied if the parent object had a scaling value. This would have made collider bound appear invalid and could have been the original cause of your problem (if you used scaling on any collider).

**Comment by XMatrixXiang** [comment]
Thanks for the quick response.
I compiled the latest code. and  made a simple scene (a quad node with the PlaneCollider, and a Box node with the BoxCollider )
this is the information about the quad node. 

![1](https://user-images.githubusercontent.com/13548583/41191481-e6cea6b2-6c22-11e8-9254-8454ee933877.png)

this is the information about the box node
![2](https://user-images.githubusercontent.com/13548583/41191488-0547fb70-6c23-11e8-96b0-e88096613d70.png)
This is the initial state(To illustrate the problem, I deliberately set like this)
![3](https://user-images.githubusercontent.com/13548583/41191497-205790d8-6c23-11e8-9b98-2b21aabf527d.png)
when I click the play button. the box  fell to the ground.
![end](https://user-images.githubusercontent.com/13548583/41191638-335fb79e-6c25-11e8-87f7-a4aa23f69fda.png)

the  BoxCollider gizmo should not be plugged into the ground.
What you said in your reply is right, so I should say that the BoxCollider gizmo’s transform not properly reflecting the The real effect

**Comment by BearishSun** [comment]
Thanks for the detailed report, it really helped to track down the issue quickly.

Your first guess was pretty close, rotation was being applied twice to the local offset, but only in a specific circumstance. I believe it should be resolved now.

**Comment by XMatrixXiang** [comment]
Thanks， Checked and it's good ！
