### ISSUE TITLE
Tolerate a passed null pointer for the interface "BansheeEngine::bs_delete"?

### ISSUE THREAD

**Issue by elfring** [BearishSun/BansheeEngine#48]
- How do you think about to support an approach that [a template function like "`bs_delete`"](https://github.com/BearishSun/BansheeEngine/blob/7c1b1c1d03e7f42a02bcd6575a0b579f9fc9b4c8/Source/BansheeUtility/Include/BsMemoryAllocator.h#L262) can also tolerate a passed null pointer?
- Would you like to avoid any extra checks at [other source code places](http://docs.banshee3d.com/Native/group___memory.html#gab7f1d8bc0be937b506afc5caae288b1f) then?

**Comment by BearishSun** [comment]
That introduces a branch instruction whenever bs_delete is called, even when the caller is sure the parameter is not null. I'd rather not force those extra CPU cycles for what is a very small convenience.

**Comment by elfring** [comment]
Can this software design decision trigger unwanted "branch instructions" at other places?

Would you add null pointer tolerance as a feature like it is provided by similar well-known interfaces?
* [C++ delete operator](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?")
* [C function "`free`"](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?")

Would a "safer" and "more convenient" interface fit also into this class library?

**Comment by BearishSun** [comment]
Yes, both delete and free tolerate null pointers so you pay the cost of that check whether you want it or not. It's not a lot of extra cycles, especially since heap allocations are expensive anyway, but no reason to pay it if it can be avoided.

Adding "bs_delete_safe" that does perform null checks would be acceptable.

**Comment by elfring** [comment]
How do you think about to configure the feature "null pointer tolerance" by a corresponding template parameter?

**Comment by BearishSun** [comment]
I'd prefer a different function name rather than a template parameter. It's clearer on what the function does. Template parameters would be more useful if there was more code reuse but the implementation of bs_delete is pretty simple.

**Comment by elfring** [comment]
Can we get both software design possibilities?
* Would you like to distinguish a bit more between functions that tolerate any null items like pointers (and "handles")?
* Where would you still prefer to pass an "intolerant function object" as a template parameter?

**Comment by elfring** [comment]
I would appreciate a more constructive feedback for this issue.

**Comment by BearishSun** [comment]
Answers to your questions:
 - No. Because I don't think this is an issue that deserves as nearly as much attention as it was given in this thread. Generally if something doesn't tolerate a null pointer it shouldn't accept a pointer, it should accept a reference (which is how it is done almost everywhere in Banshee). If this ever becomes a problem in practice I'll consider either changing the current behavior or adding a different method.
 - I can't think of any places.

**Comment by elfring** [comment]
We got different views around the preferred null pointer handling.
I imagine that advanced template programming can help more to improve remaining open issues around this use case.
