### ISSUE TITLE
Banshee assert failed and projects not compiling (source preview commit b47a79b)

### ISSUE THREAD

**Issue by HungryDoodles** [BearishSun/BansheeEngine#52]
I've used OpenGL and OpenAudio in CMake options, tried to build engine by myself, it launched with build errors (see Compilation log down below), but there is assertion error appeared right on startup (Line 612). Reason: result of getting parameter index is InvalidType, possibly because I used OpenGL.
![assertionfailescreenshot](https://cloud.githubusercontent.com/assets/15637319/19040324/08620c7a-899d-11e6-90c2-c37fc32c2964.png)

[Compilation log](https://github.com/BearishSun/BansheeEngine/files/506403/Output.txt)

**Comment by BearishSun** [comment]
OpenGL isn't up to date on that commit, and will not work. I am currently in the process of getting OpenGL functional again, and if you get the latest from master, it should work, for the most part.

The compile errors are due to the fact that all projects get included in VS builds, even if you don't select them in CMake. To avoid building those projects don't build the entire solution, but rather just build the BansheeEditorExec or ExampleProject projects, which will automatically build only the necessary dependencies. This has also been improved on the master branch, and all projects are no longer included in the VS solution by default, as it was causing confusion.
