### ISSUE TITLE
Missing (generated?) files in master?

### ISSUE THREAD

**Issue by almightykiwi** [BearishSun/BansheeEngine#56]
Hi,

I have a pull request coming soon, but I tried to rebase on `master`, and cmake complains about a bunch of files missing. What should I do?

Here is cmake's output:

```
CMake Error at BansheeSL/CMakeLists.txt:8 (file):
  file RENAME failed to rename

    /home/karot/dev/banshee/Source/BansheeSL/BsLexerFX.h

  to

    /home/karot/dev/banshee/Source/BansheeSL/Include/BsLexerFX.h

  because: No such file or directory



CMake Error at BansheeSL/CMakeLists.txt:9 (file):
  file RENAME failed to rename

    /home/karot/dev/banshee/Source/BansheeSL/BsLexerFX.c

  to

    /home/karot/dev/banshee/Source/BansheeSL/Source/BsLexerFX.c

  because: No such file or directory



CMake Error at BansheeSL/CMakeLists.txt:10 (file):
  file RENAME failed to rename

    /home/karot/dev/banshee/Source/BansheeSL/BsParserFX.h

  to

    /home/karot/dev/banshee/Source/BansheeSL/Include/BsParserFX.h

  because: No such file or directory



CMake Error at BansheeSL/CMakeLists.txt:11 (file):
  file RENAME failed to rename

    /home/karot/dev/banshee/Source/BansheeSL/BsParserFX.c

  to

    /home/karot/dev/banshee/Source/BansheeSL/Source/BsParserFX.c

  because: No such file or directory
```

**Comment by BearishSun** [comment]
Hey.

Those files are generated by executing flex & bison tools with the following command line (on Windows):
 - flex.exe --wincompat ${PROJECT_SOURCE_DIR}/BansheeSL/BsLexerFX.l
 - bison.exe ${PROJECT_SOURCE_DIR}/BansheeSL/BsParserFX.y

The files are then copied to their appropriate folders. This is done in BansheeSL/CMakeLists.txt, but the generation code is Windows specific, and there is no equivalent code on Linux, which is why the files are missing. 

Depending on how much work you want to do, you can either:
 - Manually generate the required files using flex/bison and copy them to relevant folders. Also wrap the platform specific code that calls flex/bison in CMakeLists with if(WIN32) to stop it from executing on Linux. 
 - Or you can try to fix the CMakeLists.txt file so it properly calls flex/bison and copies the files.

**Comment by BearishSun** [comment]
Optionally, if you don't care about BansheeSL library compiling, you can just add dummy files with the appropriate file names + add the if(WIN32) in CMakeLists.txt.

**Comment by BearishSun** [comment]
Assuming fixed due to your PR.
