### ISSUE TITLE
Fatal Error on new project creation 

### ISSUE THREAD

**Issue by ArchaicMage** [BearishSun/BansheeEngine#59]
Running BansheeEditorExec.exe from prebuilt binaries v0.4, v0.4p1 and creating a new project results in InternalErrorException. I have included two screens. You can access an archive containing the .html and .dmp files [here](https://www.dropbox.com/s/ewnjwjerg68jnfw/20161126_1337.7z?dl=0).

I am running Windows 10 x64. I received 0.4p1 from [here](https://github.com/BearishSun/BansheeEngine/issues/49). I was tracing down that issue on startup initially.

Please let me know if I can be of any assistance.

![20161126 - fatalerror](https://cloud.githubusercontent.com/assets/12578432/20642528/168810ee-b3df-11e6-971d-b7c10a78a2ae.png)
![20161126 - stacktrace](https://cloud.githubusercontent.com/assets/12578432/20642527/1642cdd6-b3df-11e6-98f7-874e3fc56271.png)

**Comment by BearishSun** [comment]
Hi. The error seems to indicate a corrupt file in the project.

The log in the first screenshot seems to imply you are trying to create a project over an existing project. Could you try creating it in a brand new folder and see if the same issue happens?

**Comment by ArchaicMage** [comment]
I still receive the 'Copy operation failed' message with the creation of a new project however, the Editor no longer crashes upon project creation.

I was initially attempting to create a new Banshee project within a directory containing empty 'Dependencies' and 'Resources' directories.

**Comment by BearishSun** [comment]
I managed to reproduce the "Copy operation failed" warning, and fix it locally. It was happening when creating a new project while having another project currently open.

But aside from the warning it shouldn't have caused any real issues. And I'm unable to reproduce the original issue. Any chance you tried creating project in that folder previous to this attempt, and it failed due to some other crash (or something else that might have corrupted a file)?

**Comment by ArchaicMage** [comment]
It is possible. I will try and reproduce there exception.

**Comment by ArchaicMage** [comment]
After multiple attempts, I am unable to reproduce this issue.
