### ISSUE TITLE
OpenGL & DX9 error

### ISSUE THREAD

**Issue by dragonCASTjosh** [BearishSun/BansheeEngine#6]
after i downloaded the source i managed to sucsessfully compile and run in DX11 render mode but after changing it to other render systems (including the shader and shader compile target to the correct api) it crashes after creating the window with the break point at invalid default shaders. i would find get you a line and fine but im currently working on d3d12 implementation using the engine

**Comment by BearishSun** [comment]
The available development version is very unstable (there was little to no testing done). Only testing done was using the example using DX11, so it's possible some issue specific to DX9 and OpenGL snuck by. Be aware that any bug reports on this version are unlikely to be looked at because the current version of the engine been has changed significantly so they are most likely obsolete. However the next development preview of the engine should be released later this year which will be more stable.

**Comment by dragonCASTjosh** [comment]
awesome i look forward to it
