### ISSUE TITLE
Changing the Default Shaders / Adding built in material shaders

### ISSUE THREAD

**Issue by dragonCASTjosh** [BearishSun/BansheeEngine#61]
I have made changes to the Diffuse.bsl and Default.bsl in the hopes to have new shaders for a project I'm working on (check you mail) but the shader do not change in the editor and new samples are not shown. I'm not sure if its something I'm missing as it seems the shaders need to be compiled into .asset files

**Comment by BearishSun** [comment]
Hey. The builtin shaders should recompile and update the relevant .asset files the first time you run the engine after the change. This only happens when running under the Debug configuration in VS. Perhaps that's the problem?

The actual code that triggers this recompile is in BsBuiltinResources.cpp, under BuiltinResources constructor. You can also try checking there if everything gets called properly.

However you shouldn't have the need to modify builtin shaders, as you can also create your own shaders without modifying the built-in ones. If using the editor you can add new shader file (or just copy the Diffuse.bsl one) to the project and just assign it to a Material (by default the material will use the Standard shader, which is the Diffuse.bsl one, but you can switch to Custom and assign your own).

I haven't received an e-mail :/ Where did you send it?

**Comment by dragonCASTjosh** [comment]
it was likely because i was running release, im building debug right now, as for the email i sent it through the website

**Comment by BearishSun** [comment]
I didn't get it. Could you retry sending it through the website? Just to confirm if that is somehow busted.

But also send it directly to marko.pintera@gmail.com

**Comment by dragonCASTjosh** [comment]
resent through website, ill also direct email you just to be safe

**Comment by dragonCASTjosh** [comment]
Debug build didnt compile, so im going to do a full recompile and see if that helps

**Comment by dragonCASTjosh** [comment]
seems deleting the current .asset files caused it to recompile

**Comment by BearishSun** [comment]
Deleting the Timestamp.asset file, or changing any of the files in the Data/Raw folder technically should cause it to recompile. Anyway, closing the issue as it appears resolved.
