### ISSUE TITLE
Why don't make an internal editor?

### ISSUE THREAD

**Issue by RealAquilus** [BearishSun/BansheeEngine#63]
Really an internal Editor like how Stingray/CocosCreator have, when you click on script it is popued and you can edit it. How Godot and Atomic have is also good, but the "pop-uped" version is better.
Really, visual studio/monodevelop are slow, SharpDevelop is ok, visual studio code better. But have an internal editor would be REALLY perfect. Take in consideration this man! Thanks for all your works :)

Sorry for my english i'm studying for improve it.

**Comment by BearishSun** [comment]
A simple internal code editor could be fine for small projects, but for large projects professional users will want advanced refactoring, navigation and debugging features. Implementing all such features in an internal editor would be a massive undertaking on its own - and the only benefit I can see is reducing the time to load Visual Studio initially for a few seconds (since I haven't noticed any slowness aside from that - not sure if you're referring to something else).

That said, I will be adding support for other editors like VS Code, but it's unlikely I will ever have the time to develop an internal editor that can match the feature-set of existing external code editors.

**Comment by lamarpavel** [comment]
Some of these features could be achieved by invoking an external editor with a pre-populated file and then reading the returned data when the editor closes. I would assume many editors support this, at least vim and emacs do.

**Comment by BearishSun** [comment]
That is how Banshee's integration with Visual Studio currently works. A project file is generated by Banshee and opened by VS. Any changes made in VS are reflected in Banshee's Editor when saved.

Similar support will be added for other type of external editors, once supported.
